/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tdm5.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <dirent.h>

uint64_t authenticate(struct svc_req *rqstp) {
	struct authunix_parms *aup;

	if(rqstp->rq_cred.oa_flavor == AUTH_UNIX) {
		aup = (struct authunix_parms *) rqstp->rq_clntcred;
		if(aup->aup_uid != getuid()) {
			printf("Failed to authenticate client");
			return 0xdeadbeef;
		}
	}
	return 0;
}

liste *ls_1_svc(filename *dirname, struct svc_req *rqstp)
{
	static liste result;
	uint64_t authentication;

	if((authentication = authenticate(rqstp))) {
		result = (liste) authentication;
		return &result;
	}

	liste firstEntry = malloc(sizeof(cellule));
	liste currentName;

	DIR* currentDirectory;
	struct dirent *dir;

	if((currentDirectory = opendir(*dirname)) == NULL) {
		perror("[-] opendir");
		result = NULL;
		return &result;
	}

	currentName = firstEntry;

	while(dir = readdir(currentDirectory)) {
		printf("[+] %s\n", dir->d_name);
		currentName->name = dir->d_name;
		currentName->next_cell = malloc(sizeof(cellule));
		currentName = currentName->next_cell;
	}

	currentName->next_cell = NULL;

	result = firstEntry;

	if(closedir(currentDirectory) == -1) {
		perror("[-] Closedir");
	}

	return &result;
}

content_list *readfile_1_svc(filename *argp, struct svc_req *rqstp)
{
	static content_list result;
	uint64_t authentication;

	if((authentication = authenticate(rqstp))) {
		result = (content_list) authentication;
		return &result;
	}

	FILE *filefd;

	if((filefd = fopen(*argp, "r")) == NULL) {
		perror("[-] fopen");
		result = NULL;
		return &result;
	}

	contentbuf buf = malloc(MAXBUF);

	content_list firstEntry = malloc(sizeof(content_cell));
	content_list currentEntry;

	currentEntry = firstEntry;

	printf("Serving file content \"%s\"\n", *argp);

	while(fgets(buf, MAXBUF + 1, filefd) != NULL) {
		printf("%s", buf);
		currentEntry->content = buf;
		currentEntry->next_cell = malloc(sizeof(content_cell));
		currentEntry = currentEntry->next_cell;
		buf = malloc(MAXBUF);
	}

	currentEntry->next_cell = NULL;

	if(fclose(filefd)) {
		perror("[-] fclose");
		result = NULL;
		return &result;
	}	

	result = firstEntry;

	return &result;
}


int *writefile_1_svc(params_write *argp, struct svc_req *rqstp)
{
	static int result;
	uint64_t authentication;

	if((authentication = authenticate(rqstp))) {
		result = authentication;
		return &result;
	}

	FILE *filefd;

	char *mode = argp->ecraser ? "w" : "a";

	if((filefd = fopen(argp->name, mode)) == NULL) {
		perror("[-] fopen\n");
		result = -1;
		return &result;
	}

	fprintf(filefd, argp->data, strlen(argp->data));

	if(fclose(filefd)) {
		perror("[-] fclose");
		result = -1;
		return &result;
	}

	return &result;
}
