/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TDM5_H_RPCGEN
#define _TDM5_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 255
#define MAXBUF 1024

typedef char *filename;

typedef char *contentbuf;

typedef struct cellule *liste;

struct cellule {
	filename name;
	liste next_cell;
};
typedef struct cellule cellule;

typedef struct content_cell *content_list;

struct content_cell {
	contentbuf content;
	content_list next_cell;
};
typedef struct content_cell content_cell;


struct params_write {
	filename name;
	int ecraser;
	contentbuf data;
};
typedef struct params_write params_write;

#define TDM5 0x20000001
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define LS 1
extern  liste * ls_1(filename *, CLIENT *);
extern  liste * ls_1_svc(filename *, struct svc_req *);
#define READFILE 2
extern  content_list * readfile_1(filename *, CLIENT *);
extern  content_list * readfile_1_svc(filename *, struct svc_req *);
#define WRITEFILE 3
extern  int * writefile_1(params_write *, CLIENT *);
extern  int * writefile_1_svc(params_write *, struct svc_req *);
extern int tdm5_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LS 1
extern  liste * ls_1();
extern  liste * ls_1_svc();
#define READFILE 2
extern  content_list * readfile_1();
extern  content_list * readfile_1_svc();
#define WRITEFILE 3
extern  int * writefile_1();
extern  int * writefile_1_svc();
extern int tdm5_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_contentbuf (XDR *, contentbuf*);
extern  bool_t xdr_liste (XDR *, liste*);
extern  bool_t xdr_cellule (XDR *, cellule*);
extern  bool_t xdr_content_list (XDR *, content_list*);
extern  bool_t xdr_content_cell (XDR *, content_cell*);
extern  bool_t xdr_params_write (XDR *, params_write*);
extern  bool_t xdr_params_write (XDR *, params_write*);

#else /* K&R C */
extern bool_t xdr_filename ();
extern bool_t xdr_contentbuf ();
extern bool_t xdr_liste ();
extern bool_t xdr_cellule ();
extern bool_t xdr_content_list ();
extern bool_t xdr_content_cell ();
extern bool_t xdr_params_write ();
extern bool_t xdr_params_write ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TDM5_H_RPCGEN */
