/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tdm5.h"

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNOM))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_contentbuf (XDR *xdrs, contentbuf *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXBUF))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_liste (XDR *xdrs, liste *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct cellule), (xdrproc_t) xdr_cellule))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cellule (XDR *xdrs, cellule *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_liste (xdrs, &objp->next_cell))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_content_list (XDR *xdrs, content_list *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct content_cell), (xdrproc_t) xdr_content_cell))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_content_cell (XDR *xdrs, content_cell *objp)
{
	register int32_t *buf;

	 if (!xdr_contentbuf (xdrs, &objp->content))
		 return FALSE;
	 if (!xdr_content_list (xdrs, &objp->next_cell))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_params_write (XDR *xdrs, params_write *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ecraser))
		 return FALSE;
	 if (!xdr_contentbuf (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}
